<?php
/* $Id: audio_myspace.module,v 1.1 2006/11/13 20:57:17 leob Exp $ */

/**
 * @file
 * Adds a 'add to MySpace' link to audio entries.
 * 
 */

/**
 * Required files
 */
 

/**
 * Implementation of hook_help().
 */
function audio_myspace_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t("Adds a 'add to MySpace' link to audio entries.");
    case 'admin/help#audio_myspace':
      return t("Adds a 'add to MySpace' link to audio entries.");
  }
}

/**
 * Implementation of hook_menu().
 */
function audio_myspace_menu($may_cache) {
  global $user;
  $items = array();

  if ($may_cache) {
  } 
  else if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if ($node->type == 'audio') {
        $items[] = array('path' => 'node/'. arg(1) .'/myspace', 
          'title' => t('myspace popup'),
          'type' => MENU_CALLBACK,
          'callback' => '_audio_myspace_callback',
          'callback arguments' => array($node)
          );
    }
  }
  
  return $items;
}


/**
 *  Menu Callback. Displays a new pop up window with instructions on how to embed the personal audio_playlist in MySpace.
 */
function _audio_myspace_callback($audio_node) {
  if (!node_access('view', $audio_node)) {
    drupal_access_denied();
    return;
  }
  print theme('audio_myspace_popup', $audio_node);
}


/**
 * Implementation of hook_link.
 */
function audio_myspace_link($type, $node, $teaser = FALSE) {
  $links = array();
  if ($type == 'node' && $node->type == 'audio') {
      $text = t('add to myspace');
      $description = t('include audio player in a myspace profile');
      $links[] = theme('audio_myspace_link', $node->nid, $text, $description);
  }
  return $links;
}


/**
 *  Format a popup myspace link.
 */
function theme_audio_myspace_link($nid, $title, $description) {
  global $base_url;
  $url = $base_url.'/?q=node/'. $nid .'/myspace';
  $height = 120;
  $width = 450;

  $output =  '<a class="popup-link" onclick="window.open('.check_plain('"'.$url.'", null,"height='.$height.',width='.$width.',status=no,toolbar=no,menubar=no,location=no,resizable=no,scrollbars=yes"').')" title="'.$description.'">'.$title.'</a>';

  return $output;
} 

/**
  *  This function returns the html needed for the myspace popup window.
  */
function theme_audio_myspace_popup($audio_node) {
  $title = t('Add to MySpace profile');

  $options = array('autoplay' => FALSE);
  $code = audio_get_player($audio_node);

  $body = '<div id="main"><div class="profile">';
  $form['audio_myspace_popup'] = array(
    '#type' => 'textfield',
    '#size' => 65,
    '#maxlength' => '800',
    '#title' => t('Add audio player to MySpace'),
    '#default_value' => $code,
    '#description' => t('To get an audio player like this %player, copy the above HTML code into your MySpace profile.', array('%player' => $code)),
    '#attributes' => array('readonly' => 'readonly'),    // Need to add this attribute in order to have a read-only field
  );
  $body .= drupal_get_form('_audio_myspace_popup_form', $form);
  $body .= '</div></div>';

  $title = check_plain($title);
  $output = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"';
  $output .= ' "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';
  $output .= ' <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">';
  $output .= '<head>';
  $output .= '<title>'. $title .'</title>';
  $output .= drupal_get_html_head();
  $output .= theme_get_styles();
  $output .= ' </head>';
  $output .= '<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">' . $body .'</body>';
  $output .= '</html>';

  return $output;
}

