<?php
// $Id: location.ve.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Venezuela

function location_province_list_ve() {
  return array('Z' => "Amazonas",
    'B' => "Anzoategui",
    'C' => "Apure",
    'D' => "Aragua",
    'E' => "Barinas",
    'F' => "Bolivar",
    'G' => "Carabobo",
    'H' => "Cojedes",
    'Y' => "Delta Amacuro",
    'I' => "Falcon",
    'J' => "Guarico",
    'K' => "Lara",
    'L' => "Merida",
    'M' => "Miranda",
    'N' => "Monagas",
    'O' => "Nueva Esparta",
    'P' => "Portuguesa",
    'R' => "Sucre",
    'S' => "Tachira",
    'T' => "Trujillo",
    'X' => "Vargas",
    'U' => "Yaracuy",
    'V' => "Zulia",
    'A' => "Federal District",
    'W' => "Federal Dependency");
}

?>