<?php
// $Id: location.dm.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Dominica

function location_province_list_dm() {
  return array('AND' => "Saint Andrew Parish",
    'DAV' => "Saint David Parish",
    'GEO' => "Saint George Parish",
    'JOH' => "Saint John Parish",
    'JOS' => "Saint Joseph Parish",
    'LUK' => "Saint Luke Parish",
    'MAR' => "Saint Mark Parish",
    'PAT' => "Saint Patrick Parish",
    'PAU' => "Saint Paul Parish",
    'PET' => "Saint Peter Parish");
}

?>