<?php
// $Id: location.mw.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Malawi

function location_province_list_mw() {
  return array('BLK' => "Balaka",
    'BLT' => "Blantyre",
    'CKW' => "Chikwawa",
    'CRD' => "Chiradzulu",
    'CTP' => "Chitipa",
    'DDZ' => "Dedza",
    'DWA' => "Dowa",
    'KRG' => "Karonga",
    'KSG' => "Kasungu",
    'LKM' => "Likoma",
    'LLG' => "Lilongwe",
    'MCG' => "Machinga",
    'MGC' => "Mangochi",
    'MCH' => "Mchinji",
    'MLJ' => "Mulanje",
    'MWZ' => "Mwanza",
    'MZM' => "Mzimba",
    'NTU' => "Ntcheu",
    'NKB' => "Nkhata Bay",
    'NKH' => "Nkhotakota",
    'NSJ' => "Nsanje",
    'NTI' => "Ntchisi",
    'PHL' => "Phalombe",
    'RMP' => "Rumphi",
    'SLM' => "Salima",
    'THY' => "Thyolo",
    'ZBA' => "Zomba");
}

?>