<?php
// $Id: location.ao.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Angola

function location_province_list_ao() {
  return array('BGO' => "Bengo",
    'BGU' => "Benguela province",
    'BIE' => "Bie",
    'CAB' => "Cabinda",
    'CCU' => "Cuando-Cubango",
    'CNO' => "Cuanza Norte",
    'CUS' => "Cuanza Sul",
    'CNN' => "Cunene",
    'HUA' => "Huambo province",
    'HUI' => "Huila province",
    'LUA' => "Luanda",
    'LNO' => "Lunda Norte",
    'LSU' => "Lunda Sul",
    'MAL' => "Malange",
    'MOX' => "Moxico",
    'NAM' => "Namibe",
    'UIG' => "Uige",
    'ZAI' => "Zaire");
}

?>