<?php
// $Id: location.pg.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Papua New Guinea

function location_province_list_pg() {
  return array('BV' => "Bougainville",
    'CE' => "Central",
    'CH' => "Chimbu",
    'EH' => "Eastern Highlands",
    'EB' => "East New Britain",
    'ES' => "East Sepik",
    'EN' => "Enga",
    'GU' => "Gulf",
    'MD' => "Madang",
    'MN' => "Manus",
    'MB' => "Milne Bay",
    'MR' => "Morobe",
    'NC' => "National Capital",
    'NI' => "New Ireland",
    'NO' => "Northern",
    'SA' => "Sandaun",
    'SH' => "Southern Highlands",
    'WE' => "Western",
    'WH' => "Western Highlands",
    'WB' => "West New Britain");
}

?>