<?php
// $Id: location.nl.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Netherlands

function location_province_list_nl() {
  return array('DR' => "Drenthe",
    'FL' => "Flevoland",
    'FR' => "Friesland",
    'GE' => "Gelderland",
    'GR' => "Groningen",
    'LI' => "Limburg",
    'NB' => "Noord Brabant",
    'NH' => "Noord Holland",
    'OV' => "Overijssel",
    'UT' => "Utrecht",
    'ZE' => "Zeeland",
    'ZH' => "Zuid Holland");
}

?>