<?php
// $Id: location.ge.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Georgia

function location_province_list_ge() {
  return array('AB' => "Abkhazia",
    'AJ' => "Ajaria",
    'TB' => "Tbilisi",
    'GU' => "Guria",
    'IM' => "Imereti",
    'KA' => "Kakheti",
    'KK' => "Kvemo Kartli",
    'MM' => "Mtskheta-Mtianeti",
    'RL' => "Racha Lechkhumi and Kvemo Svaneti",
    'SZ' => "Samegrelo-Zemo Svaneti",
    'SJ' => "Samtskhe-Javakheti",
    'SK' => "Shida Kartli");
}

?>