<?php
// $Id: location.ec.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Ecuador

function location_province_list_ec() {
  return array('A' => "Azuay",
    'B' => "Bolivar",
    'C' => "Carchi",
    'D' => "Orellana",
    'E' => "Esmeraldas",
    'F' => "Canar",
    'G' => "Guayas",
    'H' => "Chimborazo",
    'I' => "Imbabura",
    'L' => "Loja",
    'M' => "Manabi",
    'N' => "Napo",
    'O' => "El Oro",
    'P' => "Pichincha",
    'R' => "Los Rios",
    'S' => "Morona-Santiago",
    'T' => "Tungurahua",
    'U' => "Sucumbios",
    'W' => "Galapagos",
    'X' => "Cotopaxi",
    'Y' => "Pastaza",
    'Z' => "Zamora-Chinchipe");
}

?>