<?php
// $Id: location.eg.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Egypt

function location_province_list_eg() {
  return array('DHY' => "Ad Daqahliyah",
    'BAM' => "Al Bahr al Ahmar",
    'BHY' => "Al Buhayrah",
    'FYM' => "Al Fayyum",
    'GBY' => "Al Gharbiyah",
    'IDR' => "Al Iskandariyah",
    'IML' => "Al Isma'iliyah",
    'JZH' => "Al Jizah",
    'MFY' => "Al Minufiyah",
    'MNY' => "Al Minya",
    'QHR' => "Al Qahirah",
    'QLY' => "Al Qalyubiyah",
    'WJD' => "Al Wadi al Jadid",
    'SHQ' => "Ash Sharqiyah",
    'SWY' => "As Suways",
    'ASW' => "Aswan",
    'ASY' => "Asyut",
    'BSW' => "Bani Suwayf",
    'BSD' => "Bur Sa'id",
    'DMY' => "Dumyat",
    'JNS' => "Janub Sina'",
    'KSH' => "Kafr ash Shaykh",
    'MAT' => "Matruh",
    'QIN' => "Qina",
    'SHS' => "Shamal Sina'",
    'SUH' => "Suhaj");
}

?>