<?php
// $Id: location.cm.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Cameroon

function location_province_list_cm() {
  return array('ADA' => "Adamawa Province (Adamaoua)",
    'CEN' => "Centre Province",
    'EST' => "East Province (Est)",
    'EXN' => "Extreme North Province (Extrême-Nord)",
    'LIT' => "Littoral Province",
    'NOR' => "North Province (Nord)",
    'NOT' => "Northwest Province (Nord-Ouest)",
    'OUE' => "West Province (Ouest)",
    'SUD' => "South Province (Sud)",
    'SOU' => "Southwest Province (Sud-Ouest).");
}

?>