<?php
// $Id: location.lu.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Luxembourg

function location_province_list_lu() {
  return array('DD' => "Diekirch",
    'DC' => "Clervaux",
    'DR' => "Redange",
    'DV' => "Vianden",
    'DW' => "Wiltz",
    'GG' => "Grevenmacher",
    'GE' => "Echternach",
    'GR' => "Remich",
    'LL' => "Luxembourg",
    'LC' => "Capellen",
    'LE' => "Esch-sur-Alzette",
    'LM' => "Mersch");
}

?>