<?php
// $Id: location.sy.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Syrian Arab Republic

function location_province_list_sy() {
  return array('HA' => "Al Hasakah",
    'LA' => "Al Ladhiqiyah",
    'QU' => "Al Qunaytirah",
    'RQ' => "Ar Raqqah",
    'SU' => "As Suwayda",
    'DA' => "Dara",
    'DZ' => "Dayr az Zawr",
    'DI' => "Dimashq",
    'HL' => "Halab",
    'HM' => "Hamah",
    'HI' => "Hims",
    'ID' => "Idlib",
    'RD' => "Rif Dimashq",
    'TA' => "Tartus");
}

?>