<?php
// $Id: location.ma.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Morocco

function location_province_list_ma() {
  return array('AGD' => "Agadir",
    'HOC' => "Al Hoceima",
    'AZI' => "Azilal",
    'BME' => "Beni Mellal",
    'BSL' => "Ben Slimane",
    'BLM' => "Boulemane",
    'CBL' => "Casablanca",
    'CHA' => "Chaouen",
    'EJA' => "El Jadida",
    'EKS' => "El Kelaa des Sraghna",
    'ERA' => "Er Rachidia",
    'ESS' => "Essaouira",
    'FES' => "Fes",
    'FIG' => "Figuig",
    'GLM' => "Guelmim",
    'IFR' => "Ifrane",
    'KEN' => "Kenitra",
    'KHM' => "Khemisset",
    'KHN' => "Khenifra",
    'KHO' => "Khouribga",
    'LYN' => "Laayoune",
    'LAR' => "Larache",
    'MRK' => "Marrakech",
    'MKN' => "Meknes",
    'NAD' => "Nador",
    'ORZ' => "Ouarzazate",
    'OUJ' => "Oujda",
    'RSA' => "Rabat-Sale",
    'SAF' => "Safi",
    'SET' => "Settat",
    'SKA' => "Sidi Kacem",
    'TGR' => "Tangier",
    'TAN' => "Tan-Tan",
    'TAO' => "Taounate",
    'TRD' => "Taroudannt",
    'TAT' => "Tata",
    'TAZ' => "Taza",
    'TET' => "Tetouan",
    'TIZ' => "Tiznit",
    'ADK' => "Ad Dakhla",
    'BJD' => "Boujdour",
    'ESM' => "Es Smara");
}

?>