<?php
// $Id: location.lr.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Liberia

function location_province_list_lr() {
  return array('BI' => "Bomi",
    'BG' => "Bong",
    'GB' => "Grand Bassa",
    'CM' => "Grand Cape Mount",
    'GG' => "Grand Gedeh",
    'GK' => "Grand Kru",
    'LO' => "Lofa",
    'MG' => "Margibi",
    'ML' => "Maryland",
    'MS' => "Montserrado",
    'NB' => "Nimba",
    'RC' => "River Cess",
    'SN' => "Sinoe");
}

?>