<?php
// $Id: location.ye.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Yemen

function location_province_list_ye() {
  return array('AB' => "Abyan",
    'AD' => "Adan",
    'AM' => "Amran",
    'BA' => "Al Bayda",
    'DA' => "Ad Dali",
    'DH' => "Dhamar",
    'HD' => "Hadramawt",
    'HJ' => "Hajjah",
    'HU' => "Al Hudaydah",
    'IB' => "Ibb",
    'JA' => "Al Jawf",
    'LA' => "Lahij",
    'MA' => "Ma'rib",
    'MR' => "Al Mahrah",
    'MW' => "Al Mahwit",
    'SD' => "Sa'dah",
    'SN' => "San'a",
    'SH' => "Shabwah",
    'TA' => "Ta'izz");
}

?>