<?php
// $Id: location.iq.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Iraq

function location_province_list_iq() {
  return array('BD' => "Baghdad",
    'SD' => "Salah ad Din",
    'DY' => "Diyala",
    'WS' => "Wasit",
    'MY' => "Maysan",
    'BA' => "Al Basrah",
    'DQ' => "Dhi Qar",
    'MU' => "Al Muthanna",
    'QA' => "Al Qadisyah",
    'BB' => "Babil",
    'KB' => "Al Karbala",
    'NJ' => "An Najaf",
    'AB' => "Al Anbar",
    'NN' => "Ninawa",
    'DH' => "Dahuk",
    'AL' => "Arbil",
    'TM' => "At Ta'mim",
    'SL' => "As Sulaymaniyah");
}

?>