<?php
// $Id: location.cu.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Cuba

function location_province_list_cu() {
  return array('IJU' => "Isla de la Juventud",
    'PRI' => "Pinar del Rio",
    'LHA' => "La Habana",
    'CLH' => "Ciudad de La Habana",
    'MAT' => "Matanzas",
    'CFU' => "Cienfuegos",
    'VCL' => "Villa Clara",
    'SSP' => "Sancti Spiritus",
    'CAV' => "Ciego de Avila",
    'CAM' => "Camaguey",
    'LTU' => "Las Tunas",
    'GRA' => "Granma",
    'HOL' => "Holguin",
    'SCU' => "Santiago de Cuba",
    'GUA' => "Guantanamo");
}

?>