<?php
// $Id: location.cf.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Central African Republic

function location_province_list_cf() {
  return array('BBA' => "Bamingui-Bangoran",
    'BKO' => "Basse-Kotto",
    'HKO' => "Haute-Kotto",
    'HMB' => "Haut-Mbomou",
    'KEM' => "Kemo",
    'LOB' => "Lobaye",
    'MKD' => "Mambere-Kadeï",
    'MBO' => "Mbomou",
    'NMM' => "Nana-Mambere",
    'OMP' => "Ombella-M'Poko",
    'OUK' => "Ouaka",
    'OUH' => "Ouham",
    'OPE' => "Ouham-Pende",
    'VAK' => "Vakaga",
    'NGR' => "Nana-Grebizi",
    'SMB' => "Sangha-Mbaere",
    'BAN' => "Bangui");
}

?>