<?php
// $Id: location.bm.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Bermuda

function location_province_list_bm() {
  return array('DS' => "Devonshire",
    'HC' => "Hamilton City",
    'HA' => "Hamilton",
    'PG' => "Paget",
    'PB' => "Pembroke",
    'GC' => "Saint George City",
    'SG' => "Saint George's",
    'SA' => "Sandys",
    'SM' => "Smith's",
    'SH' => "Southampton",
    'WA' => "Warwick");
}

?>