<?php
// $Id: location.ua.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Ukraine

function location_province_list_ua() {
  return array('CK' => "Cherkasy",
    'CH' => "Chernihiv",
    'CV' => "Chernivtsi",
    'CR' => "Crimea",
    'DN' => "Dnipropetrovs'k",
    'DO' => "Donets'k",
    'IV' => "Ivano-Frankivs'k",
    'KL' => "Kharkiv Kherson",
    'KM' => "Khmel'nyts'kyy",
    'KR' => "Kirovohrad",
    'KV' => "Kiev",
    'KY' => "Kyyiv",
    'LU' => "Luhans'k",
    'LV' => "L'viv",
    'MY' => "Mykolayiv",
    'OD' => "Odesa",
    'PO' => "Poltava",
    'RI' => "Rivne",
    'SE' => "Sevastopol",
    'SU' => "Sumy",
    'TE' => "Ternopil'",
    'VI' => "Vinnytsya",
    'VO' => "Volyn'",
    'ZK' => "Zakarpattya",
    'ZA' => "Zaporizhzhya",
    'ZH' => "Zhytomyr");
}

?>