<?php
// $Id: location.ee.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Estonia

function location_province_list_ee() {
  return array('37' => "Harju County",
    '39' => "Hiiu County",
    '44' => "Ida-Viru County",
    '49' => "Jõgeva County",
    '51' => "JArva County",
    '57' => "LAAne County",
    '59' => "LAAne-Viru County",
    '65' => "Põlva County",
    '67' => "PArnu County",
    '70' => "Rapla County",
    '74' => "Saare County",
    '78' => "Tartu County",
    '82' => "Valga County",
    '84' => "Viljandi County",
    '86' => "Võru County");
}

?>