<?php
// $Id: location.gt.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Guatemala

function location_province_list_gt() {
  return array('AV' => "Alta Verapaz",
    'BV' => "Baja Verapaz",
    'CM' => "Chimaltenango",
    'CQ' => "Chiquimula",
    'PE' => "El Peten",
    'PR' => "El Progreso",
    'QC' => "El Quiche",
    'ES' => "Escuintla",
    'GU' => "Guatemala",
    'HU' => "Huehuetenango",
    'IZ' => "Izabal",
    'JA' => "Jalapa",
    'JU' => "Jutiapa",
    'QZ' => "Quetzaltenango",
    'RE' => "Retalhuleu",
    'ST' => "Sacatepequez",
    'SM' => "San Marcos",
    'SR' => "Santa Rosa",
    'SO' => "Solola",
    'SU' => "Suchitepequez",
    'TO' => "Totonicapan",
    'ZA' => "Zacapa");
}

?>