<?php
// $Id: location.tz.inc,v 1.2 2006/03/08 06:53:39 dww Exp $

// Tanzania, United Republic of

function location_province_list_tz() {
  return array('AR' => "Arusha",
    'DS' => "Dar es Salaam",
    'DO' => "Dodoma",
    'IR' => "Iringa",
    'KA' => "Kagera",
    'KI' => "Kigoma",
    'KJ' => "Kilimanjaro",
    'LN' => "Lindi",
    'MY' => "Manyara",
    'MR' => "Mara",
    'MB' => "Mbeya",
    'MO' => "Morogoro",
    'MT' => "Mtwara",
    'MW' => "Mwanza",
    'PN' => "Pemba North",
    'PS' => "Pemba South",
    'PW' => "Pwani",
    'RK' => "Rukwa",
    'RV' => "Ruvuma",
    'SH' => "Shinyanga",
    'SI' => "Singida",
    'TB' => "Tabora",
    'TN' => "Tanga",
    'ZC' => "Zanzibar Central/South",
    'ZN' => "Zanzibar North",
    'ZU' => "Zanzibar Urban/West");
}

?>