<?php
// $Id: location.gh.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Ghana

function location_province_list_gh() {
  return array('AS' => "Ashanti Region",
    'BA' => "Brong-Ahafo Region",
    'CE' => "Central Region",
    'EA' => "Eastern Region",
    'GA' => "Greater Accra Region",
    'NO' => "Northern Region",
    'UE' => "Upper East Region",
    'UW' => "Upper West Region",
    'VO' => "Volta Region",
    'WE' => "Western Region");
}

?>