<?php
// $Id: location.cl.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Chile

function location_province_list_cl() {
  return array('AI' => "Aisen del General Carlos Ibanez del Campo (XI)",
    'AN' => "Antofagasta (II)",
    'AR' => "Araucania (IX)",
    'AT' => "Atacama (III)",
    'BI' => "Bio-Bio (VIII)",
    'CO' => "Coquimbo (IV)",
    'LI' => "Libertador General Bernardo O'Higgins (VI)",
    'LL' => "Los Lagos (X)",
    'MA' => "Magallanes (XII)",
    'ML' => "Maule (VII)",
    'RM' => "Region Metropolitana (RM)",
    'TA' => "Tarapaca (I)",
    'VS' => "Valparaiso (V)");
}

?>