<?php
// $Id: location.na.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Namibia

function location_province_list_na() {
  return array('CA' => "Caprivi",
    'ER' => "Erongo",
    'HA' => "Hardap",
    'KR' => "Karas",
    'KV' => "Kavango",
    'KH' => "Khomas",
    'KU' => "Kunene",
    'OW' => "Ohangwena",
    'OK' => "Omaheke",
    'OT' => "Omusati",
    'ON' => "Oshana",
    'OO' => "Oshikoto",
    'OJ' => "Otjozondjupa");
}

?>