<?php
// $Id: location.ck.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Cook Islands

function location_province_list_ck() {
  return array('PU' => "Pukapuka",
    'RK' => "Rakahanga",
    'MK' => "Manihiki",
    'PE' => "Penrhyn",
    'NI' => "Nassau Island",
    'SU' => "Surwarrow",
    'PA' => "Palmerston",
    'AI' => "Aitutaki",
    'MA' => "Manuae",
    'TA' => "Takutea",
    'MT' => "Mitiaro",
    'AT' => "Atiu",
    'MU' => "Mauke",
    'RR' => "Rarotonga",
    'MG' => "Mangaia");
}

?>