<?php
// $Id: location.kp.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Korea, Democratic People's Republic Of (North Korea)

function location_province_list_kp() {
  return array('CHA' => "Chagang-do",
    'HAB' => "Hamgyong-bukto",
    'HAN' => "Hamgyong-namdo",
    'HWB' => "Hwanghae-bukto",
    'HWN' => "Hwanghae-namdo",
    'KAN' => "Kangwon-do",
    'PYB' => "P'yongan-bukto",
    'PYN' => "P'yongan-namdo",
    'YAN' => "Ryanggang-do (Yanggang-do)",
    'NAJ' => "Rason Directly Governed City",
    'PYO' => "P'yongyang Special City");
}

?>