<?php
// $Id: location.cd.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Congo, The Democratic Republic of the

function location_province_list_cd() {
  return array('BC' => "Bas-Congo",
    'BN' => "Bandundu",
    'EQ' => "Equateur",
    'KA' => "Katanga",
    'KE' => "Kasai-Oriental",
    'KN' => "Kinshasa",
    'KW' => "Kasai-Occidental",
    'MA' => "Maniema",
    'NK' => "Nord-Kivu",
    'OR' => "Orientale",
    'SK' => "Sud-Kivu");
}

?>