<?php
// $Id: location.gm.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Gambia

function location_province_list_gm() {
  return array('BJ' => "Banjul",
    'BS' => "Basse",
    'BR' => "Brikama",
    'JA' => "Janjangbure",
    'KA' => "Kanifeng",
    'KE' => "Kerewan",
    'KU' => "Kuntaur",
    'MA' => "Mansakonko",
    'LR' => "Lower River",
    'CR' => "Central River",
    'NB' => "North Bank",
    'UR' => "Upper River",
    'WE' => "Western");
}

?>