<?php
// $Id: location.kn.inc,v 1.2 2006/03/08 06:53:38 dww Exp $

// Saint Kitts and Nevis

function location_province_list_kn() {
  return array('CCN' => "Christ Church Nichola Town",
    'SAS' => "Saint Anne Sandy Point",
    'SGB' => "Saint George Basseterre",
    'SGG' => "Saint George Gingerland",
    'SJW' => "Saint James Windward",
    'SJC' => "Saint John Capesterre",
    'SJF' => "Saint John Figtree",
    'SMC' => "Saint Mary Cayon",
    'CAP' => "Saint Paul Capesterre",
    'CHA' => "Saint Paul Charlestown",
    'SPB' => "Saint Peter Basseterre",
    'STL' => "Saint Thomas Lowland",
    'STM' => "Saint Thomas Middle Island",
    'TPP' => "Trinity Palmetto Point");
}

?>